# Generated by Django 3.0.1 on 2021-05-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0002_auto_20210529_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
