# Generated by Django 3.0.1 on 2021-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerPassword',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
