# Generated by Django 3.0.1 on 2021-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20210522_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerEmail',
            field=models.CharField(blank=True, default='abc@gmail.com', max_length=50),
        ),
    ]
