# Generated by Django 3.0.1 on 2021-05-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_customer_customeremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
